version: "3"

services:
  rvc:
    build:
      context: .
      target: final
      args:
        - RVC_TAG=updated1006v2
        - PYTHON_VERSION=3.9.18
        - RUNTIME_USERNAME=rvc
    image: ghcr.io/pycabbage/rvc-docker:master
    runtime: nvidia
    ports:
      - 7897:7897
    volumes:
      - ./assets:/app/assets
      - ./logs:/app/logs
      - ./opt:/app/opt
