name: Build Docker Image

on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'RVC tag to build'
        required: true
        default: "updated1006v2"
      python_version:
        description: 'Python version to build'
        required: true
        default: "3.10.13"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  RVC_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || 'updated1006v2' }}
  PYTHON_VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.python_version || '3.10.13' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.registry }}/${{ github.repository }}
        tags: |
          latest
          ${{ github.sha }}
          ${{ github.ref }}
          ${{ env.RVC_TAG }}
          ${{ env.RVC_TAG }}-${{ env.PYTHON_VERSION }}
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.registry }}
        username: ${{ env.username }}
        password: ${{ env.password }}
    - uses: docker/build-push-action@v5
      with:
        pull: true
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: final
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          RVC_TAG=${{ env.RVC_TAG }}
          PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          RUNTIME_USERNAME=rvc
          RUNTIME_GROUPNAME=rvc
          RUNTIME_UID=1000
          RUNTIME_GID=1000
